#用清华大学的镜像源
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

#修改工程名后pod 指定项目名
project 'ProjectDemo.xcodeproj'

def shared_pods

pod 'BDBSDiskCache', :git => 'git@git.wozaijia.com:iOS/DiskCache.git',:tag => '1.0.1'
end

target "ProjectDemo" do
shared_pods
end
